# Generated by Django 5.2.6 on 2025-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.AddField(
            model_name='sessions',
            name='text',
            field=models.CharField(default='xxxx', max_length=1000),
        ),
    ]
