# Generated by Django 5.2.6 on 2025-09-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_delete_reason_sessions_text'),
        ('therapy', '0004_therapists_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='text',
        ),
        migrations.AddField(
            model_name='sessions',
            name='reason',
            field=models.TextField(default='xxxxxx'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='therapist',
            field=models.ForeignKey(default='xxxxx', on_delete=django.db.models.deletion.CASCADE, to='therapy.therapists'),
        ),
    ]
