# Generated by Django 5.2.6 on 2025-09-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_remove_sessions_text_sessions_reason_and_more'),
        ('therapy', '0004_therapists_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='therapist',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='therapy.therapists'),
        ),
    ]
