# Generated by Django 5.2.6 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_sessions_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='day',
            field=models.CharField(default='xxxx', max_length=100),
        ),
    ]
