# Generated by Django 5.2.6 on 2025-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_sessions_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
