# Generated by Django 5.2.6 on 2025-10-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_alter_sessions_day'),
        ('therapy', '0004_therapists_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.therapists'),
        ),
    ]
