# Generated by Django 5.2.6 on 2025-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_sessions_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='reason',
            field=models.TextField(default='xxxxxx'),
        ),
    ]
