# Generated by Django 5.2.6 on 2025-11-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_alter_sessions_reason'),
        ('therapy', '0004_therapists_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='therapy.therapists'),
        ),
    ]
