# Generated by Django 5.2.6 on 2025-11-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_alter_sessions_therapist'),
        ('patients', '0002_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient'),
        ),
    ]
