# Generated by Django 5.2.6 on 2025-12-12 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_sessions_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
