# Generated by Django 5.2.6 on 2026-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_sessions_created_at_sessions_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='sessions',
            name='reason_category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='sessions',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
