# Generated by Django 5.2.6 on 2026-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_sessions_duration_minutes_sessions_reason_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
