# Generated by Django 5.2.6 on 2026-03-12 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("super_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("is_primary_admin", models.BooleanField(default=True)),
                ("can_add_therapists", models.BooleanField(default=True)),
                ("can_edit_org_settings", models.BooleanField(default=True)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins",
                        to="super_admin.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Admin",
                "verbose_name_plural": "Organization Admins",
                "db_table": "org_admin",
            },
        ),
        migrations.CreateModel(
            name="OrgActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("therapist_added", "Therapist Added"),
                            ("therapist_edited", "Therapist Edited"),
                            ("therapist_deactivated", "Therapist Deactivated"),
                            ("settings_updated", "Settings Updated"),
                            ("code_changed", "Organization Code Changed"),
                            ("member_imported", "Members Imported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="super_admin.organization",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="org_admin.orgadmin",
                    ),
                ),
            ],
            options={
                "db_table": "org_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_member", models.BooleanField(default=True)),
                ("new_session", models.BooleanField(default=True)),
                ("session_cancelled", models.BooleanField(default=True)),
                ("weekly_report", models.BooleanField(default=False)),
                ("monthly_report", models.BooleanField(default=True)),
                (
                    "org_admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to="org_admin.orgadmin",
                    ),
                ),
            ],
            options={
                "db_table": "org_notification_preferences",
            },
        ),
    ]
