# Generated by Django 5.2.6 on 2026-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgadmin",
            name="accept_public_patients",
            field=models.BooleanField(
                default=False,
                help_text="Allow non-members to book sessions with org therapists for a fee",
            ),
        ),
        migrations.AddField(
            model_name="orgadmin",
            name="public_session_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=4000.0,
                help_text="Rate for non-members booking org therapists (KES)",
                max_digits=10,
            ),
        ),
    ]
