# Generated by Django 5.2.6 on 2026-03-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_admin", "0002_orgadmin_accept_public_patients_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgadmin",
            name="accept_public_patients",
        ),
        migrations.RemoveField(
            model_name="orgadmin",
            name="public_session_rate",
        ),
    ]
