# Generated by Django 5.2.6 on 2025-12-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
