# Generated by Django 5.2.6 on 2026-03-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("consultation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionnotes",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="consultation.sessions",
            ),
        ),
    ]
