# Generated by Django 5.2.6 on 2025-12-13 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_timestamp_messages_created_at'),
        ('consultation', '0012_sessions_created_at_sessions_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultation.sessions'),
        ),
    ]
