# Generated by Django 5.2.6 on 2026-01-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_is_read_alter_messages_session'),
        ('consultation', '0014_alter_sessions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='consultation.sessions')),
            ],
            options={
                'unique_together': {('session', 'user_id', 'user_type')},
            },
        ),
    ]
