# Generated by Django 5.2.6 on 2026-02-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='xxxx', max_length=255)),
                ('lastName', models.CharField(default='xxxx', max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(default='xxxx@gmail.com', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='therapists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='xxxx', max_length=255)),
                ('lastName', models.CharField(default='xxxx', max_length=255)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('email', models.EmailField(default='xxxx@gmai.com', max_length=255)),
                ('description', models.CharField(default='A certified Therapist', max_length=400)),
                ('profile_pic', models.ImageField(upload_to='therapists/')),
                ('specialty_1', models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True)),
                ('specialty_2', models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True)),
                ('specialty_3', models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time_slot', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='therapy.therapists')),
            ],
            options={
                'ordering': ['day_of_week', 'time_slot'],
                'unique_together': {('therapist', 'day_of_week', 'time_slot')},
            },
        ),
    ]
