# Generated by Django 5.2.6 on 2025-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapists',
            name='email',
            field=models.EmailField(default='xxxx@gmai.com', max_length=255),
        ),
        migrations.AddField(
            model_name='therapists',
            name='firstName',
            field=models.CharField(default='xxxx', max_length=255),
        ),
        migrations.AddField(
            model_name='therapists',
            name='lastName',
            field=models.CharField(default='xxxx', max_length=255),
        ),
        migrations.AddField(
            model_name='therapists',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
