# Generated by Django 5.2.6 on 2025-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_therapists_email_therapists_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='xxxx', max_length=255)),
                ('lastName', models.CharField(default='xxxx', max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(default='xxxx@gmail.com', max_length=255)),
            ],
        ),
    ]
