# Generated by Django 5.2.6 on 2026-02-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_remove_therapists_email_therapists_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patients',
        ),
    ]
