# Generated by Django 5.2.6 on 2026-02-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_delete_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
