# Generated by Django 5.2.6 on 2025-09-25 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapists',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='therapists/'),
            preserve_default=False,
        ),
    ]
