# Generated by Django 5.2.6 on 2026-03-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super_admin", "0001_initial"),
        ("therapy", "0004_alter_therapists_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapists",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapists",
                to="super_admin.organization",
            ),
        ),
    ]
