# Generated by Django 5.2.6 on 2026-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0005_therapists_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapists",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
