# Generated by Django 5.2.6 on 2026-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_therapistavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapists',
            name='specialty_1',
            field=models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapists',
            name='specialty_2',
            field=models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='therapists',
            name='specialty_3',
            field=models.CharField(blank=True, choices=[('academic_pressure', 'Academic Pressure'), ('anger_management', 'Anger Management'), ('anxiety_stress', 'Anxiety / Stress'), ('burnout', 'Burnout / Work-related Stress'), ('chronic_illness', 'Chronic Illness'), ('depression', 'Depression'), ('family_problems', 'Family Problems'), ('grief_loss', 'Grief / Loss'), ('identity_issues', 'Identity Issues'), ('life_transitions', 'Life Transitions'), ('parenting_issues', 'Parenting Challenges'), ('relationship_issues', 'Relationship Issues'), ('self_esteem', 'Self-esteem Issues'), ('sleep_issues', 'Sleep Problems'), ('social_anxiety', 'Social Anxiety'), ('substance_use', 'Substance Use'), ('trauma_ptsd', 'Trauma / PTSD'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
