# Generated by Django 5.2.6 on 2026-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0006_therapists_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapists",
            name="session_rate_45",
            field=models.DecimalField(
                decimal_places=2,
                default=2500.0,
                help_text="Rate for 45-minute sessions (KES)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="therapists",
            name="session_rate_60",
            field=models.DecimalField(
                decimal_places=2,
                default=3000.0,
                help_text="Rate for 60-minute sessions (KES)",
                max_digits=10,
            ),
        ),
    ]
