# Generated by Django 5.2.6 on 2026-03-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("super_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="super_admin.organization",
            ),
        ),
    ]
