# Generated by Django 5.2.6 on 2026-03-09 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("company", "Company"),
                            ("ngo_free", "Non-Profit (Free Services)"),
                            ("ngo_subsidized", "Non-Profit (Subsidized)"),
                            ("government", "Government Agency"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "organization_code",
                    models.CharField(
                        help_text="Code members use to join (e.g., UON2024)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("admin_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("subscription", "Monthly Subscription"),
                            ("free", "Free (Community Partner)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_members", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("subscription_start", models.DateField(auto_now_add=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("allow_self_registration", models.BooleanField(default=True)),
                ("require_admin_approval", models.BooleanField(default=False)),
                ("logo", models.ImageField(blank=True, upload_to="org_logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sso_enabled", models.BooleanField(default=False)),
                ("sso_provider", models.CharField(blank=True, max_length=50)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_organization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_type", models.CharField(max_length=100)),
                ("recipient", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="super_admin.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("org_created", "Organization Created"),
                            ("org_updated", "Organization Updated"),
                            ("org_deactivated", "Organization Deactivated"),
                            ("therapist_added", "Therapist Added"),
                            ("patient_registered", "Patient Registered"),
                            ("session_completed", "Session Completed"),
                            ("payment_processed", "Payment Processed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="super_admin.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("can_create_organizations", models.BooleanField(default=True)),
                ("can_delete_organizations", models.BooleanField(default=True)),
                ("can_view_all_data", models.BooleanField(default=True)),
                ("can_modify_system_settings", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="super_admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
            },
        ),
    ]
