# Generated by Django 5.2.6 on 2025-11-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0002_message_is_read'),
        ('consultation', '0011_sessions_patient'),
        ('therapy', '0004_therapists_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_patient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='therapist',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='therapy.therapists'),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultation.sessions'),
        ),
    ]
